apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: maintainers
spec:
  type: team
  children: []

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: internal-plugin-todo-list
  title: '@internal/plugin-todo-list'
spec:
  type: backstage-frontend-plugin
  lifecycle: experimental
  owner: group:default/maintainers
