apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fstestrepo
  annotations:
    github.com/project-slug: suremine-cts/fstestrepo
spec:
  type: other
  lifecycle: unknown
  owner: guests
